main: DiamondStrider1\BetterMinigames\BMG
version: 0.0.1
api: 3.21.1

name: BetterMinigames
author: DiamondStrider1
description: A plugin for Pocketmine which adds support for various minigames.
website: https://github.com/Swift-Strider/BetterMinigames

commands:
    bmg:
        description: Admin command for managing minigames
        usage: /bmg ...
        permission: better-minigames.manage
permissions:
    better-minigames.alert:
        description: Alerts players with this permission when the config has errors or warnings
        default: op
    better-minigames.manage:
        description: Allows adding, removing, and customizing minigames on the server.
        default: op
